# Dependencies
markdown:         kramdown  # redcarpet 대신 github pages 표준인 kramdown 권장
highlighter:      rouge     # pygments 대신 rouge 권장

# Permalinks
permalink:        pretty

# Setup
title:            "Junsu Lee"
tagline:          'A Jekyll theme'
description:      'Derrick Lee의 포트폴리오 사이트입니다.'
url:              "https://Junsu-Lee-01.github.io"
baseurl:          "" # 이 부분을 반드시 비워주세요

author:
  name:           'Derrick (Junsu) Lee'
  url:            "https://www.linkedin.com/in/derrick-junsu-lee"

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Junsu-Lee-01/Junsu-Lee-01.github.io
